### ISSUE TITLE
Minimum time between you've got mail messages

### ISSUE THREAD

**Issue by retep998** [FTB-Gamepedia/SatanicBot#108]
Currently the bot will repeat the `You've got mail (# unread)! Use the checkmail command to check your mail!` message each time you send a message. Instead it should have a minimum time between such messages, so that after it tells someone they've got mail, it shouldn't send another such message to that person until a certain amount of time has elapsed.

**Comment by elifoster** [comment]
What amount of time?

**Comment by retep998** [comment]
Maybe 5 minutes?
