### ISSUE TITLE
Aggregate identical messages

### ISSUE THREAD

**Issue by retep998** [FTB-Gamepedia/SatanicBot#109]
If two identical messages are sent to the same person, instead of adding a new message, it should simply increase a counter.

That way we could have something like `(16:08:37) LittleHelper: xbony2|afk: sokratis12GR said 100 times "OK WHEN IT GETS TO 100"`

**Comment by xbony2** [comment]
Also there's my suggestion of blocking users.

**Comment by elifoster** [comment]
@retep998 If someone only had, say, 100 identical messages, and no other ones, would it still do the rainbow thing?

**Comment by retep998** [comment]
@elifoster I think rainbow should be based on number of unique messages.
