### ISSUE TITLE
Mod list additions (and probably other things) not being marked as bot

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/SatanicBot#123]
[This](https://ftb.gamepedia.com/index.php?title=Module:Mods/list&diff=559936&oldid=559755&rcid=&curid=29725) (among other additions) showed up in RC as not a bot change.

**Comment by elifoster** [comment]
Ah yeah, this is because of FTB-Gamepedia/MediaWiki-Butt-Ruby#60. I'll keep this up to remind me to upgrade MW butt once I fix that.
