### ISSUE TITLE
Disable sending of duplicate messages

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/SatanicBot#132]
(using $tell, in case you are confused)

**Comment by elifoster** [comment]
What do you mean?

**Comment by xbony2** [comment]
Do $checkmail and then you'll see :^)

**Comment by elifoster** [comment]
(for my reference)
```

[10:00:19] <@SatanicSanta> $checkmail
[10:00:19] <@LittleHelper> You have 4 unread messages. Reading...
[10:00:19] <@LittleHelper> SatanicSanta: xbony2 says "uuuuu" from #FTB-Wiki at August  3 2017 16:11:34 UTC 2 times
[10:00:19] <@LittleHelper> SatanicSanta: xbony2 says "uuuuu" from #FTB-Wiki at August  3 2017 16:11:46 UTC
[10:00:19] <@LittleHelper> SatanicSanta: Hubry says "uuuuu?" from #FTB-Wiki at August  3 2017 16:12:01 UTC
[10:00:20] <@LittleHelper> Finished reading unread messages. Deleted 4 messages.
```

This looks more like a checkmail issue than a tell issue. It should
* Only include the timestamp when there is 1 message, or maybe include a time range if > 1?
* Not send the message multiple times if it says it was sent multiple times.

**Comment by xbony2** [comment]
Interesting that $checkmail already has some support for duplicate messages. But I think it still makes more sense with $tell; if you send a duplicate message, it should just say "you already sent this on August 3rd, 2017" (or something). There's no serious applications to being able to send duplicate messages as far as I'm concerned.

**Comment by elifoster** [comment]
I see your point. It could be used, however, to show that the thing you sent is *really* important.

**Comment by xbony2** [comment]
I think that's dumb, if it's important find some other way to emphasize it.

I think that's dumb, if it's important find some other way to emphasize it.

I think that's dumb, if it's important find some other way to emphasize it.

I think that's dumb, if it's important find some other way to emphasize it.

I think that's dumb, if it's important find some other way to emphasize it.

I think that's dumb, if it's important find some other way to emphasize it.

I think that's dumb, if it's important find some other way to emphasize it.

I think that's dumb, if it's important find some other way to emphasize it.

I think that's dumb, if it's important find some other way to emphasize it.

**Comment by elifoster** [comment]
Mail system has been removed since this is now a Discord bot.
