### ISSUE TITLE
$getabbrv broke

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/SatanicBot#149]
`$getabbrv V`, `$getabbrv Twilight Forest`, etc., does nothing. Very weird since it was working a few hours ago and there have been no changes to the mod list in about a week.

The bot isn't down because I can do `$help` before and after an abbreviation request. I'm testing this in IRC, seems my bridge bot went down around the same time. Could be a blip in the fabric of reality, but I would recommend checking whatever logs you have.

**Comment by elifoster** [comment]
Is this still an issue? Are other wiki commands broken too?

**Comment by xbony2** [comment]
Still an issue. `$checkpage Main Page` doesn't work either so perhaps there's some issue with authentication.

**Comment by elifoster** [comment]
Got it fixed. Just needed to confirm my email address on the bot's Fandom account (actually I had to do it 3-4 times but...).
