### ISSUE TITLE
System message auto-translator

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/SatanicBot#80]
A bot should be created to automatically copy "es" [system messages](http://ftb.gamepedia.com/index.php?title=Special%3AAllMessages) to "es-ni". ESAEBSAD doesn't have sysop abilities, so you have to make this yourself.

**Comment by elifoster** [comment]
Not all of those messages can be copied exactly from es to es-ni. I'll just have to translate them manually.

**Comment by elifoster** [comment]
@xbony2 Why did you close this?

**Comment by elifoster** [comment]
@xbony2 Why did you close this?

**Comment by xbony2** [comment]
It's not really an issue related to your bot if you plan to translate them manually.
