### ISSUE TITLE
Delete own messages

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/SatanicBot#99]
People should be able to delete messages that they send to people, before they get read.

**Comment by elifoster** [comment]
Currently, I think the best way to do this would to add two commands.
1. $getsent, which PRIVMSGs the user with all of their sent and unread mail. It will give them the ID of the message, which they can use in
2. $deletemsg <id> Provide the actual primary key ID to delete a message before the recipient reads it.

What do you think @retep998 and @xbony2 (since I know you love the mail system so much)

**Comment by retep998** [comment]
I hold no opinion

**Comment by xbony2** [comment]
Maybe you should add a blocking system too, to block mean users.
